README.md
Added by Ravi- This PR merges with main branch for base project
=> PR to update Readme

Documentation/One_Persona.md, README.md
=> 5 create document one persona

Documentation/Customer_Journey.md
=> Updated Sales Funnel/Customer Journey

Documentation/Competitive_Analysis.md
=> Updated Competitive Analysis

Documentation/SWOT_Analysis.md
=> Updated SWOT Analysis

jr-cafe/tests/project.spec.js
=> Test written for title

jr-cafe/tests/project.spec.js
=> Test written for Navbar

jr-cafe/tests/project.spec.js
=> Test written for Hero

jr-cafe/tests/project.spec.js
=> Test written for About Section. Closes #41

jr-cafe/tests/project.spec.js
=> Test written for call to action

jr-cafe/tests/project.spec.js
=> Test written for Email Input Box

jr-cafe/tests/project.spec.js
=> Test written for Menu Section

jr-cafe/tests/project.spec.js
=> Test written for accordian element

jr-cafe/src/app/Gallery/page.tsx, jr-cafe/src/app/Menu/page.tsx, jr-cafe/tests/project.spec.js
=> 46 create playwright test for gallery section

jr-cafe/tests/project.spec.js
=> Test written for all pages - social section

jr-cafe/tests/project.spec.js
=> Test written for all pages - location

jr-cafe/tests/project.spec.js
=> Added Meta Description Test

jr-cafe/tests/project.spec.js
=> Added Email Anchor Test

jr-cafe/tests/project.spec.js
=> Added Instagram Test

jr-cafe/tests/project.spec.js
=> Added Twitter Test

jr-cafe/src/app/layout.tsx
=> Updated SEO Description

jr-cafe/src/app/Header/page.tsx, jr-cafe/src/app/globals.css
=> Updated Navbar

README.md
=> Added Powerpoint link

jr-cafe/src/app/Subscribe/page.tsx, jr-cafe/src/app/page.tsx
=> Fixed email input form
